import type { Metadata } from "next";
import "./bootstrap-italia.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <head></head>
      <body>{children}</body>
    </html>
  );
}
